//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPlaner {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirPlaner.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        public static string btnOkay {
            get {
                return ResourceManager.GetString("btnOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save &amp; Close ähnelt.
        /// </summary>
        public static string btnSaveAndClose {
            get {
                return ResourceManager.GetString("btnSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Airline Settings ähnelt.
        /// </summary>
        public static string createGameAirlineGBCaption {
            get {
                return ResourceManager.GetString("createGameAirlineGBCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Airline Settings ähnelt.
        /// </summary>
        public static string createGameAirlineSettingsCaption {
            get {
                return ResourceManager.GetString("createGameAirlineSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Airline Name ähnelt.
        /// </summary>
        public static string createGameAirlineSettingsName {
            get {
                return ResourceManager.GetString("createGameAirlineSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must enter a airline name ähnelt.
        /// </summary>
        public static string createGameErrorAirlineNameMissing {
            get {
                return ResourceManager.GetString("createGameErrorAirlineNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must enter a firstname and lastname ähnelt.
        /// </summary>
        public static string createGameErrorNameMissing {
            get {
                return ResourceManager.GetString("createGameErrorNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player Settings ähnelt.
        /// </summary>
        public static string createGameUserSettingsCaption {
            get {
                return ResourceManager.GetString("createGameUserSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Picture... ähnelt.
        /// </summary>
        public static string createGameUserSettingsChangePicture {
            get {
                return ResourceManager.GetString("createGameUserSettingsChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        public static string createGameUserSettingsFirstname {
            get {
                return ResourceManager.GetString("createGameUserSettingsFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playername ähnelt.
        /// </summary>
        public static string createGameUserSettingsGBCaption {
            get {
                return ResourceManager.GetString("createGameUserSettingsGBCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        public static string createGameUserSettingsLastname {
            get {
                return ResourceManager.GetString("createGameUserSettingsLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn Length: ähnelt.
        /// </summary>
        public static string lblTurnLength {
            get {
                return ResourceManager.GetString("lblTurnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Game ähnelt.
        /// </summary>
        public static string menuLoadGame {
            get {
                return ResourceManager.GetString("menuLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Language ähnelt.
        /// </summary>
        public static string menuLocaleTitle {
            get {
                return ResourceManager.GetString("menuLocaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string menuSettings {
            get {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Game ähnelt.
        /// </summary>
        public static string menuStartGame {
            get {
                return ResourceManager.GetString("menuStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string settingsWindowTitle {
            get {
                return ResourceManager.GetString("settingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename: ähnelt.
        /// </summary>
        public static string txtFilename {
            get {
                return ResourceManager.GetString("txtFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        public static string txtLoading {
            get {
                return ResourceManager.GetString("txtLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select File ähnelt.
        /// </summary>
        public static string txtSelectFile {
            get {
                return ResourceManager.GetString("txtSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 day ähnelt.
        /// </summary>
        public static string txtTurnOneDay {
            get {
                return ResourceManager.GetString("txtTurnOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 month ähnelt.
        /// </summary>
        public static string txtTurnOneMonth {
            get {
                return ResourceManager.GetString("txtTurnOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 week ähnelt.
        /// </summary>
        public static string txtTurnOneWeek {
            get {
                return ResourceManager.GetString("txtTurnOneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 weeks ähnelt.
        /// </summary>
        public static string txtTurnTwoWeeks {
            get {
                return ResourceManager.GetString("txtTurnTwoWeeks", resourceCulture);
            }
        }
    }
}
